import fs from "fs";
import { execSync } from "child_process";
import { z } from "zod";
import { pgDb } from "../db";
import {
  candidatesList,
  activeCandidateId,
  setActiveCandidateId
} from "../state/tradingState";
import { safetyBackstop } from "../../safetyBackstop";
import { addServerLog } from "./logging";

export function isCodeWhitelisted(code: string): boolean {
  // Remove comments
  const cleanCode = code.replace(/\/\/.*$/gm, "").replace(/\/\*[\s\S]*?\*\//g, "");
  
  // Whitelist of valid words/identifiers for reward mathematics
  const allowedWords = new Set([
    "double", "float", "int", "return", "if", "else", "calculateReward",
    "std", "pow", "abs", "exp", "max", "min", "sqrt", "log",
    "pnl_pips", "execution_latency_ns", "slippage_ticks", "volatility_spike", "position_lots",
    "pnl_reward", "slippage_penalty", "sniper_speed_bonus", "shock_factor",
    "base", "penalty", "vol", "reward", "factor", "hybrid", "synthesis",
    "trend", "flat", "mean", "reversion", "variance", "regime", "smooth",
    "smoothed", "signal", "decay", "alpha", "beta", "filter", "kalman",
    "gain", "state", "attention", "weight", "weighted", "drawdown",
    "penalty_sq", "quadratic", "linear", "multiplier", "offset", "constant",
    "score", "threshold", "val", "x", "y", "z", "temp", "limit", "bound",
    "extern", "C",
    // Standard safe modifiers & types
    "const", "static", "constexpr", "inline", "void", "bool", "true", "false",
    // Compiler directives & standard library headers
    "include", "define", "cmath", "algorithm", "vector", "numeric",
    // Helper names frequently generated by optimization or heuristics
    "speed_bonus", "final_reward", "speed", "bonus", "shock"
  ]);

  // Find all word tokens in the code
  const words = cleanCode.match(/[a-zA-Z_][a-zA-Z0-9_]*/g);
  if (words) {
    for (const word of words) {
      if (!allowedWords.has(word)) {
        return false; // Blocks arbitrary functions/objects (like eval, process, window, etc.)
      }
    }
  }

  // Allow only standard math characters, punctuation, quotes, brackets, and hash
  const allowedCharsRegex = /^[a-zA-Z0-9_\s\+\-\*\/\=\>\<\|\&\!\?\:\(\)\{\}\,\.\;\"\'\#\[\]\s]+$/;
  if (!allowedCharsRegex.test(cleanCode)) {
    return false;
  }

  return true;
}

export function evaluateCppRewardInJs(
  cppCode: string,
  pnl_pips: number,
  execution_latency_ns: number,
  slippage_ticks: number,
  volatility_spike: number,
  position_lots: number
): number {
  try {
    if (!isCodeWhitelisted(cppCode)) {
      console.warn("[SECURITY WARN] Blocked non-whitelisted C++ code submission");
      throw new Error("Code contains non-whitelisted tokens or characters");
    }

    let cleanCode = cppCode.replace(/\/\/.*$/gm, "").replace(/\/\*[\s\S]*?\*\//g, "");
    cleanCode = cleanCode
      .replace(/double\s+calculateReward\s*\([^)]*\)\s*\{/, "")
      .trim();
    
    if (cleanCode.endsWith("}")) {
      cleanCode = cleanCode.slice(0, -1).trim();
    }

    const lines = cleanCode.split(";");
    const scope: Record<string, any> = {
      pnl_pips,
      execution_latency_ns,
      slippage_ticks,
      volatility_spike,
      position_lots,
      sniper_speed_bonus: 0,
      pnl_reward: 0,
      slippage_penalty: 0,
      shock_factor: 1.0
    };

    let lastEvaluatedValue: any = null;

    for (let line of lines) {
      let trimmed = line.trim();
      if (!trimmed) continue;
      if (trimmed === "}" || trimmed === "{" || trimmed === "};" || trimmed === "{;") continue;

      trimmed = trimmed.replace(/&&/g, " and ");
      trimmed = trimmed.replace(/\|\|/g, " or ");
      trimmed = trimmed.replace(/std::/g, "");

      let isReturn = false;
      if (trimmed.startsWith("return ")) {
        isReturn = true;
        trimmed = trimmed.replace("return ", "").trim();
      }

      for (const [varName, varVal] of Object.entries(scope)) {
        const regex = new RegExp(`\\b${varName}\\b`, "g");
        trimmed = trimmed.replace(regex, `(${varVal})`);
      }

      try {
        const simpleEvaluator = (expr: string) => {
          expr = expr.replace(/max\(([^,]+),([^)]+)\)/g, "Math.max($1, $2)");
          expr = expr.replace(/min\(([^,]+),([^)]+)\)/g, "Math.min($1, $2)");
          expr = expr.replace(/abs\(([^)]+)\)/g, "Math.abs($1)");
          expr = expr.replace(/pow\(([^,]+),([^)]+)\)/g, "Math.pow($1, $2)");
          expr = expr.replace(/sqrt\(([^)]+)\)/g, "Math.sqrt($1)");
          expr = expr.replace(/exp\(([^)]+)\)/g, "Math.exp($1)");
          return Function(`"use strict"; return (${expr});`)();
        };

        if (trimmed.includes("=")) {
          const parts = trimmed.split("=");
          const assignVar = parts[0].replace(/double|float|int/, "").trim();
          const expr = parts.slice(1).join("=").trim();
          const result = simpleEvaluator(expr);
          scope[assignVar] = result;
          lastEvaluatedValue = result;
        } else {
          const result = simpleEvaluator(trimmed);
          lastEvaluatedValue = result;
        }

        if (isReturn) {
          return typeof lastEvaluatedValue === "number" && !isNaN(lastEvaluatedValue) ? lastEvaluatedValue : 0;
        }
      } catch (evalErr) {
        console.warn("[MATH-EVAL] Line parse warning:", trimmed);
      }
    }

    return typeof lastEvaluatedValue === "number" && !isNaN(lastEvaluatedValue) ? lastEvaluatedValue : 0;
  } catch (err: any) {
    return 0;
  }
}

export interface SandboxResult {
  success: boolean;
  rejectionReason: string;
  metrics: {
    avgReward: number;
    maxDrawdown: number;
    SharpeRatio: number;
    tradesCount: number;
  };
}

export function executeSandboxForCandidate(name: string, code: string, creator: string): SandboxResult {
  const forbiddenKeywords = [
    "system", "popen", "fork", "exec", "socket", "fopen", "fwrite", 
    "remove", "mkdir", "rmdir", "chmod", "chown", "kill", "signal"
  ];
  
  for (const keyword of forbiddenKeywords) {
    if (code.includes(keyword)) {
      return {
        success: false,
        rejectionReason: `Static lexical scan failed: Forbidden keyword '${keyword}' detected in strategy source.`,
        metrics: { avgReward: 0, maxDrawdown: 100, SharpeRatio: 0, tradesCount: 0 }
      };
    }
  }

  if (!isCodeWhitelisted(code)) {
    return {
      success: false,
      rejectionReason: "Security violation: C++ code contains unapproved syntax or symbols.",
      metrics: { avgReward: 0, maxDrawdown: 100, SharpeRatio: 0, tradesCount: 0 }
    };
  }

  const tempFile = `/tmp/candidate_${Date.now()}_adopt.cpp`;
  try {
    fs.writeFileSync(tempFile, code, "utf8");
    execSync(`bash evolution_validator.sh ${tempFile}`, { stdio: "pipe" });
  } catch (err: any) {
    const errMsg = err.stderr ? err.stderr.toString() : err.message || "Unknown compile/audit error";
    try { fs.unlinkSync(tempFile); } catch(_) {}
    return {
      success: false,
      rejectionReason: `C++ compiler audit or static verification failed: ${errMsg.substring(0, 300)}`,
      metrics: { avgReward: 0, maxDrawdown: 100, SharpeRatio: 0, tradesCount: 0 }
    };
  }

  try { fs.unlinkSync(tempFile); } catch(_) {}

  const historicalTicks = pgDb.query("SELECT * FROM historical_ticks") || [];
  if (historicalTicks.length === 0) {
    return {
      success: false,
      rejectionReason: "No historical/demo ticks found in database state.",
      metrics: { avgReward: 0, maxDrawdown: 100, SharpeRatio: 0, tradesCount: 0 }
    };
  }

  let currentEquity = 10000;
  let peakEquity = 10000;
  let maxDrawdown = 0;
  let totalTrades = 0;
  const tradeReturns: number[] = [];

  for (let i = 1; i < historicalTicks.length; i++) {
    const curr = historicalTicks[i];
    const prev = historicalTicks[i-1];

    const pnlPips = (curr.price - prev.price) * 10000;
    const latency = 120 + Math.random() * 50;
    const slippage = curr.spread * 10;
    const volatility = curr.volatility;
    const size = 1.5;

    const reward = evaluateCppRewardInJs(code, pnlPips, latency, slippage, volatility, size);

    if (Math.abs(reward) > 12.0) {
      totalTrades++;
      const profit = reward * 3.5;
      currentEquity += profit;
      tradeReturns.push(profit);

      if (currentEquity > peakEquity) peakEquity = currentEquity;
      const dd = ((peakEquity - currentEquity) / peakEquity) * 100;
      if (dd > maxDrawdown) maxDrawdown = dd;
    }
  }

  let sharpeRatio = 0;
  if (tradeReturns.length >= 2) {
    const mean = tradeReturns.reduce((sum, r) => sum + r, 0) / tradeReturns.length;
    const variance = tradeReturns.reduce((sum, r) => sum + Math.pow(r - mean, 2), 0) / (tradeReturns.length - 1);
    const stdDev = Math.sqrt(variance);
    sharpeRatio = stdDev > 0 ? (mean / stdDev) * Math.sqrt(252) : 0;
  }

  const avgReward = tradeReturns.length > 0 ? tradeReturns.reduce((sum, r) => sum + r, 0) / tradeReturns.length : 0;

  const MIN_SHARPE = 1.2;
  const MAX_DRAWDOWN = 5.0;
  const MIN_TRADES = 10;

  let isPromoted = true;
  let rejectionReason = "";

  if (sharpeRatio < MIN_SHARPE) {
    isPromoted = false;
    rejectionReason += `Sharpe ratio (${sharpeRatio.toFixed(2)}) failed to clear required threshold of ${MIN_SHARPE}. `;
  }
  if (maxDrawdown > MAX_DRAWDOWN) {
    isPromoted = false;
    rejectionReason += `Max drawdown (${maxDrawdown.toFixed(2)}%) exceeded security boundary of ${MAX_DRAWDOWN}%. `;
  }
  if (totalTrades < MIN_TRADES) {
    isPromoted = false;
    rejectionReason += `Activity level of ${totalTrades} trades is below required minimum of ${MIN_TRADES}. `;
  }

  return {
    success: isPromoted,
    rejectionReason: rejectionReason.trim(),
    metrics: {
      avgReward: parseFloat(avgReward.toFixed(2)),
      maxDrawdown: parseFloat(maxDrawdown.toFixed(2)),
      SharpeRatio: parseFloat(sharpeRatio.toFixed(2)),
      tradesCount: totalTrades
    }
  };
}

export interface PromotedStrategyVersion {
  id: string;
  candidateId: string;
  name: string;
  promotedAt: string;
  code: string;
  metricsAtPromotion: any;
}

export let promotedVersionsHistory: PromotedStrategyVersion[] = [];

export function recordPromotedVersion(id: string, name: string, code: string, metrics: any) {
  const versionRecord: PromotedStrategyVersion = {
    id: `ver-${Date.now()}`,
    candidateId: id,
    name,
    promotedAt: new Date().toISOString(),
    code,
    metricsAtPromotion: metrics
  };
  promotedVersionsHistory.unshift(versionRecord);
  pgDb.query("INSERT INTO promoted_strategy_versions", [versionRecord]);
}

export const AdoptCandidateSchema = z.object({
  name: z.string().max(100).optional(),
  code: z.string().optional().default(`double calculateReward(double pnl_pips, double execution_latency_ns, double slippage_ticks, double volatility_spike, double position_lots) {\n    return pnl_pips * 10.0;\n}`).refine((val) => isCodeWhitelisted(val), {
    message: "Security violation: C++ code contains unapproved syntax or symbols."
  }),
  creator: z.string().max(50).optional(),
  metrics: z.object({
    avgReward: z.number(),
    maxDrawdown: z.number(),
    avgLatencyNs: z.number(),
    leaksBytes: z.number(),
    astWarningsCount: z.number()
  }).optional()
});

export const SelectCandidateSchema = z.object({
  id: z.string().min(1, "Candidate ID parameter is required")
});

export const BacktestSchema = z.object({
  code: z.string().min(10, "C++ Formula code is required for backtesting").refine((val) => isCodeWhitelisted(val), {
    message: "Security violation: C++ code contains unapproved syntax or symbols."
  }),
  asset: z.string().min(3, "Asset identifier (e.g. EURUSD, BTCUSD) is required"),
  duration: z.string().optional().default("1M"),
  condition: z.string().optional().default("nominal")
});
